### ISSUE TITLE
Internal Server Error for url: https://cli.promptops.com/embeddings

### ISSUE THREAD

**Issue by wgordon17** [promptops/cli#4]
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cli.promptops.com:443
DEBUG:urllib3.connectionpool:https://cli.promptops.com:443 "POST /embeddings HTTP/1.1" 200 1053734
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cli.promptops.com:443
DEBUG:urllib3.connectionpool:https://cli.promptops.com:443 "POST /embeddings HTTP/1.1" 500 35
DEBUG:root:error getting embeddings: 500 Server Error: Internal Server Error for url: https://cli.promptops.com/embeddings, {"message":"Internal Server Error"}
Traceback (most recent call last):
  File "/opt/homebrew/bin/um", line 33, in <module>
    sys.exit(load_entry_point('promptops==0.1.2', 'console_scripts', 'um')())
  File "/opt/homebrew/Cellar/promptops-cli/0.1.2/libexec/lib/python3.10/site-packages/promptops/main.py", line 116, in entry_alias
    history.update_history()
  File "/opt/homebrew/Cellar/promptops-cli/0.1.2/libexec/lib/python3.10/site-packages/promptops/history.py", line 110, in update_history
    index_history()
  File "/opt/homebrew/Cellar/promptops-cli/0.1.2/libexec/lib/python3.10/site-packages/promptops/history.py", line 97, in index_history
    for cmd, vector in embedding_batch(delta[i : i + batch_size]):
  File "/opt/homebrew/Cellar/promptops-cli/0.1.2/libexec/lib/python3.10/site-packages/promptops/history.py", line 53, in embedding_batch
    resp.raise_for_status()
  File "/opt/homebrew/Cellar/promptops-cli/0.1.2/libexec/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://cli.promptops.com/embeddings
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cli.promptops.com:443
DEBUG:urllib3.connectionpool:https://cli.promptops.com:443 "POST /feedback HTTP/1.1" 200 2
```

This is after attempting to initialize `um` after updating the package from #3. I'm not sure why it's breaking, there were many successful calls to `https://cli.promptops.com/embeddings` prior to this error.

**Comment by basilisk487** [comment]
@wgordon17 This should be fixed now - could you please try again? In this particular case it's a back-end fix so no cli update necessary

**Comment by basilisk487** [comment]
Ah - looks like you have some really long commands in your shell history. This should be fixed now as well, could you please try again @wgordon17? And we appreciate your help with making this tool better!

**Comment by wgordon17** [comment]
@basilisk487 Running it overnight did the trick, no errors, and working well now 👍
